- name: pg_hba.conf
  pg_hba:
    contype: host
    databases: "{{item[1]}}"
    dest: "{{PG_ETC}}/pg_hba.conf"
    method: trust
    source: "{{hostvars[item[0]].ansible_default_ipv4.address}}/32"
    users: postgres
  with_nested:
    - "{{groups['barman-servers']}}"
    - [ replication, postgres ]
  notify: reload postgres
  tags:
  - barman
  - barman_client
  - pg_hba

- name: 90_backup.conf
  template: src=90_backup.conf dest="{{PG_ETC}}/conf.d/90_backup.conf" force=no owner=postgres group=postgres
  register: walconf
  notify: restart postgres
  tags:
  - barman
  - barman_client
  - conf

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: check is standby
  stat:
    path: "{{ PG_DATA }}/recovery.conf"
