---
- name: clone command from barman not yet implemented
  command: "barman blaat"
  args:
    creates: "{{PG_DATA}}/PG_VERSION"
  ignore_errors: true
  notify:
  - start postgres
  - register standby
  tags:
  - cluster
  - clone

- name: clone from master
  become_user: postgres
  command: "{{PG_BIN}}/repmgr -h {{play_hosts[0]|lower}} -U repmgr -d repmgr -f {{repmgr_conf}} standby clone"
  args:
    creates: "{{PG_DATA}}/PG_VERSION"
  ignore_errors: true
  notify:
  - start postgres
  - register standby
  tags:
  - cluster
  - clone

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
