- include_tasks: repmgr_config.yml
  tags:
  - cluster
  - config
#First try to clone from barman or master
- include_tasks: clone.yml
  tags:
  - clone
  - cluster
#if clone succeeded, initdb should skip
#so initdb host0 if clone did not work
- include_tasks: initdb.yml
  when: inventory_hostname == play_hosts[0]
  tags:
  - cluster
  - initdb
- name: check cluster initted
  stat:
    path: "{{PG_ETC}}/PG_VERSION"
  register: cluster_initted
- include_tasks: pg_config.yml
  when: cluster_initted.stat.exists
  tags:
  - cluster
  - config
#clone standby if host0 was initted
- include_tasks: clone.yml
  tags:
  - cluster
  - clone
