---
- name: defaults
  template:
    src: '10_defaults.conf'
    dest: "{{PG_ETC}}/conf.d/10_defaults.conf"
    owner: postgres
    group: postgres
  notify: restart postgres
  tags:
  - cluster
  - config

- name: 91_replication.conf
  template:
    src: 91_replication.conf
    dest: "{{PG_ETC}}/conf.d/91_replication.conf"
    owner: postgres
    group: postgres
  register: walconf
  notify: restart postgres
  tags:
  - cluster
  - config
  - wal

- name: pg_hba.conf
  pg_hba: 
    databases="replication,repmgr"
    users=repmgr 
    source="{{hostvars[item].ansible_default_ipv4.address}}/32"
    method=trust
    dest="{{PG_ETC}}/pg_hba.conf"
  with_items: "{{play_hosts}}"
  register: pg_hbaconf
  notify: reload postgres
  tags:
  - cluster
  - pg_hba

- name: notify start postgres
  command: /bin/true
  changed_when: true
  notify: start postgres

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: check is_master
  become_user: postgres
  script: pg_is_master
  register: pg_is_master
  failed_when: pg_is_master.rc > 1
  tags:
  - cluster
  - setup

- include_tasks: pg_repmgr_config.yml
  when: pg_is_master.rc = 0
