---
- name: check is_master
  command: 'Not yet implemented'
  register: is_master
  tags:
  - cluster
  - setup

- name: user repmgr
  become_user: postgres
  postgresql_user: name=repmgr role_attr_flags=SUPERUSER
  when: is_master.rc = 0
  tags:
  - cluster
  - repmgr
  - pgusers

- name: searchpath
  become_user: postgres
  shell: echo 'ALTER USER repmgr SET search_path TO "repmgr_{{pg_cluster|lower}}", "$user", public;' | /usr/local/bin/psql
  tags:
  - cluster
  - setup
  - pgusers

- name: database repmgr
  become_user: postgres
  postgresql_db: name=repmgr owner=repmgr state="{{item}}"
  with_items:
    - absent
    - present
  tags:
  - cluster
  - repmgr
  - db

- name: register master
  become_user: postgres
  shell: "{{PG_BIN}}/repmgr -f {{repmgr_conf}} master register"
  tags:
  - cluster
  - repmgr
  - register
