- name: install repmgr package and some dependencies
  package:
    name: "repmgr{{PG_VERSION}},rsync"
    disable_gpg_check: true
  tags:
  - repmgr
  - packages

#- name: workaround repmgr binaries
#  file: state=link path=/usr/local/bin/repmgr src=/usr/postgres/bin/repmgr
