- include_tasks: packages.yml
- include_tasks: conf.yml
- include_tasks: user.yml
  when: inventory_hostname == play_hosts[0]
- include_tasks: rebuild_standbys.yml
  when: inventory_hostname != play_hosts[0]
