#sudo is needed for some ansible plays in this role
#ip gives ip config to ansible, so that should be installed also
- name: install package
  yum:
    name: "postgresql{{PG_VERSION}}-server,python-psycopg2,python-ipaddress"
    disable_gpg_check: true
  ignore_errors: yes
  tags:
  - postgres
  - packages

- name: create folder /etc/sysconfig/pgsql
  file:
    path: /etc/sysconfig/pgsql
    mode: 0644
    state: directory
