---
# handlers file for ansible/roles/pgcluster
- name: restart postgres
  command: /bin/true
  changed_when: true
  notify:
  - stop postgres
  - start postgres

- name: stop postgres
  become_user: postgres
  command: '{{PG_BIN}}/pg_ctl stop -D "{{PG_DATA}}"'
  args:
    removes: "/tmp/.s.PGSQL.{{PG_PORT}}"

- name: start postgres
  become_user: postgres
  command: '{{PG_BIN}}/pg_ctl start -D "{{PG_DATA}}"'
  args:
    creates: "/tmp/.s.PGSQL.{{PG_PORT}}"

- name: reload postgres
  become_user: postgres
  command: '{{PG_BIN}}/pg_ctl reload -D "{{PG_DATA}}"'
  args:
    removes: "/tmp/.s.PGSQL.{{PG_PORT}}"

- name: register standby
  become_user: postgres
  shell: "{{PG_BIN}}/repmgr -f {{repmgr_conf}} standby register"
  register: register_standby
  until: register_standby.rc ==0
  retries: 5
  delay: 10
