- name: install package
  yum:
    name: "{{item}}"
    disable_gpg_check: true
  with_items:
    - epel-release
    - "postgresql{{PG_VERSION}}"
    - barman
  tags:
  - barman
  - barman_server
  - packages
