---
- name: install epel
  yum:
    name: epel-release
  tags:
  - barman
  - barman_server
  - packages

- name: install packages
  yum:
    name: "{{item}}"
    disable_gpg_check: true
  with_items:
    - "postgresql{{PG_VERSION}}"
    - barman
  tags:
  - barman
  - barman_server
  - packages
